### ISSUE TITLE
idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网

### ISSUE THREAD

**Issue by weiwosuoai** [weiwosuoai/weiwosuoai.github.io#70]
https://www.exception.site/essay/how-to-free-use-idea-202022-by-resigter-code 

 idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效）   > 分享 idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效）

![IDEA 2020.2.2版本激活注册成功画面](https://exception-image-bucket.oss-cn-hangzhou.aliyuncs.com/160022869888225 "IDEA 2020.2.2版本激活注册成功画面")

![IDEA 2020.2.2 ..

**Comment by cc715** [comment]
也不行 重启之后弹出初始界面

**Comment by weiwosuoai** [comment]
> @cc715
> 也不行 重启之后弹出初始界面

补丁拖进去后，没把删掉吧~ 按道理不会，我这边一次就成功了的🤣

**Comment by cc715** [comment]
没删除呀 拖进去之后重启之后又回到初始界面了&nbsp; 你这两天试了没




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 下午3:46
收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)





  
@cc715
 也不行 重启之后弹出初始界面
  
补丁拖进去后，没把删掉吧~ 按道理不会，我这边一次就成功了的🤣

**Comment by weiwosuoai** [comment]
> @cc715
> 没删除呀 拖进去之后重启之后又回到初始界面了&nbsp; 你这两天试了没
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
> 发送时间:&nbsp;2020年9月25日(星期五) 下午3:46
> 收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
> 抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
> 主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)
> 
> 
> 
> 
> 
>   
> @cc715
>  也不行 重启之后弹出初始界面
>   
> 补丁拖进去后，没把删掉吧~ 按道理不会，我这边一次就成功了的🤣
>  
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020.2 版本刚发布的时候试过是ok的，你是不是之前改了 host 文件，添加了啥呢~

**Comment by weiwosuoai** [comment]
1.补丁就是不要拖进去之后，就删了，补丁放到固定的位置拖进去，之后不要更换补丁位置
2.之前版本，没有删除干净也不行，一定要删除，卸载干净
3.补丁位置和IDEA 不要装在C 盘

注意：如果提示 key is invalid ,说明agent未激活，找到C:\Users\用户名\AppData\Roaming\JetBrains下面的IntelliJIdea2020.1文件夹删掉（删掉会把所有配置都删除），重启idea

卸载干净注意事项：

删除：“C:\\Users\\User”下的 “*IntelliJIdea*”文件夹中的所有文件

比如：我的用户是“root” 那就是这个位置 C:\Users\root\AppData\Local\JetBrains\IntelliJIdea*

删除：c盘 带 IDEA 的文件夹

**Comment by cc715** [comment]
删除干净是不是就是把JetBrains目录下的所有删除掉？&nbsp; 我是放在C盘的，我在试下，版本限制到2020.2吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 中午1:14
收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)





 
1.补丁就是不要拖进去之后，就删了，补丁放到固定的位置拖进去，之后不要更换补丁位置
 2.之前版本，没有删除干净也不行，一定要删除，卸载干净
 3.补丁位置和IDEA 不要装在C 盘
 
注意：如果提示 key is invalid ,说明agent未激活，找到C:\Users\用户名\AppData\Roaming\JetBrains下面的IntelliJIdea2020.1文件夹删掉（删掉会把所有配置都删除），重启idea
 
卸载干净注意事项：
 
删除：“C:\Users\User”下的 “IntelliJIdea”文件夹中的所有文件
 
比如：我的用户是“root” 那就是这个位置 C:\Users\root\AppData\Local\JetBrains\IntelliJIdea*
 
删除：c盘 带 IDEA 的文件夹

**Comment by weiwosuoai** [comment]
> @cc715
> 删除干净是不是就是把JetBrains目录下的所有删除掉？&nbsp; 我是放在C盘的，我在试下，版本限制到2020.2吗？
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
> 发送时间:&nbsp;2020年9月26日(星期六) 中午1:14
> 收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
> 抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
> 主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)
> 
> 
> 
> 
> 
>  
> 1.补丁就是不要拖进去之后，就删了，补丁放到固定的位置拖进去，之后不要更换补丁位置
>  2.之前版本，没有删除干净也不行，一定要删除，卸载干净
>  3.补丁位置和IDEA 不要装在C 盘
>  
> 注意：如果提示 key is invalid ,说明agent未激活，找到C:\Users\用户名\AppData\Roaming\JetBrains下面的IntelliJIdea2020.1文件夹删掉（删掉会把所有配置都删除），重启idea
>  
> 卸载干净注意事项：
>  
> 删除：“C:\Users\User”下的 “IntelliJIdea”文件夹中的所有文件
>  
> 比如：我的用户是“root” 那就是这个位置 C:\Users\root\AppData\Local\JetBrains\IntelliJIdea*
>  
> 删除：c盘 带 IDEA 的文件夹
>  
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

直接在官网下最新版本的就行的哦~

**Comment by cc715** [comment]
.idea 和 IdeaProjects不用删除吧！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 中午1:33
收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)





  
@cc715
 删除干净是不是就是把JetBrains目录下的所有删除掉？&nbsp; 我是放在C盘的，我在试下，版本限制到2020.2吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
 发送时间:&nbsp;2020年9月26日(星期六) 中午1:14
 收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
 抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)
 
1.补丁就是不要拖进去之后，就删了，补丁放到固定的位置拖进去，之后不要更换补丁位置
 2.之前版本，没有删除干净也不行，一定要删除，卸载干净
 3.补丁位置和IDEA 不要装在C 盘
 
注意：如果提示 key is invalid ,说明agent未激活，找到C:\Users\用户名\AppData\Roaming\JetBrains下面的IntelliJIdea2020.1文件夹删掉（删掉会把所有配置都删除），重启idea
 
卸载干净注意事项：
 
删除：“C:\Users\User”下的 “IntelliJIdea”文件夹中的所有文件
 
比如：我的用户是“root” 那就是这个位置 C:\Users\root\AppData\Local\JetBrains\IntelliJIdea*
 
删除：c盘 带 IDEA 的文件夹
 
—
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub, or unsubscribe.
  
直接在官网下最新版本的就行的哦~

**Comment by cc715** [comment]
感谢大佬，解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 中午1:33
收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)





  
@cc715
 删除干净是不是就是把JetBrains目录下的所有删除掉？&nbsp; 我是放在C盘的，我在试下，版本限制到2020.2吗？
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "weiwosuoai/weiwosuoai.github.io"                                                                                    <notifications@github.com&gt;;
 发送时间:&nbsp;2020年9月26日(星期六) 中午1:14
 收件人:&nbsp;"weiwosuoai/weiwosuoai.github.io"<weiwosuoai.github.io@noreply.github.com&gt;;
 抄送:&nbsp;"想象之中゛yl切都会很好"<272807152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)
 
1.补丁就是不要拖进去之后，就删了，补丁放到固定的位置拖进去，之后不要更换补丁位置
 2.之前版本，没有删除干净也不行，一定要删除，卸载干净
 3.补丁位置和IDEA 不要装在C 盘
 
注意：如果提示 key is invalid ,说明agent未激活，找到C:\Users\用户名\AppData\Roaming\JetBrains下面的IntelliJIdea2020.1文件夹删掉（删掉会把所有配置都删除），重启idea
 
卸载干净注意事项：
 
删除：“C:\Users\User”下的 “IntelliJIdea”文件夹中的所有文件
 
比如：我的用户是“root” 那就是这个位置 C:\Users\root\AppData\Local\JetBrains\IntelliJIdea*
 
删除：c盘 带 IDEA 的文件夹
 
—
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub, or unsubscribe.
  
直接在官网下最新版本的就行的哦~

**Comment by JBTao** [comment]
感谢 大佬

**Comment by YoucanBaby** [comment]
失效了

**Comment by CHENbt** [comment]
使用30 天无限的方式，执行插件报错了，大佬，可以帮忙看一下吗

**Comment by CHENbt** [comment]
java.lang.NoClassDefFoundError: com/intellij/ide/util/PropertiesComponentImpl
	at io.zhile.research.intellij.ier.common.Resetter.getEvalRecords(Resetter.java:72)
	at io.zhile.research.intellij.ier.ui.form.MainForm.reloadRecordItems(MainForm.java:134)
	at io.zhile.research.intellij.ier.ui.form.MainForm.getContent(MainForm.java:99)
	at io.zhile.research.intellij.ier.tw.MainToolWindowFactory.createToolWindowContent(MainToolWindowFactory.java:23)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:528)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:507)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:850)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.kt:749)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.showToolWindow(BackendServerToolWindowManager.kt:181)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:264)
	at io.zhile.research.intellij.ier.action.ResetAction.actionPerformed(ResetAction.java:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:289)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:296)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$2(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:540)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:570)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.util.PropertiesComponentImpl PluginClassLoader(plugin=PluginDescriptor(name=IDE Eval Reset, id=io.zhile.research.ide-eval-resetter, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\ide-eval-resetter, version=2.3.5, package=null, isBundled=false), packagePrefix=null, instanceId=18, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 68 more

**Comment by weiwosuoai** [comment]
> @CHENbt
> 使用30 天无限的方式，执行插件报错了，大佬，可以帮忙看一下吗
> 

IDAE 版本是 2021.2.2 不

**Comment by CHENbt** [comment]
版本是2022.1的，之前不是搞那个copilot那个代码补全工具吗。那个工具要求版本是2021.3以后的，所以就改成.3的了，但是.3的好像破解有问题，就索性改成2022.1的了



---原始邮件---
发件人: "犬小哈教程 ***@***.***&gt;
发送时间: 2022年5月18日(周三) 上午9:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)




  
@CHENbt
 使用30 天无限的方式，执行插件报错了，大佬，可以帮忙看一下吗
  
IDAE 版本是 2021.2.2 不

**Comment by weiwosuoai** [comment]
> @CHENbt
> 版本是2022.1的，之前不是搞那个copilot那个代码补全工具吗。那个工具要求版本是2021.3以后的，所以就改成.3的了，但是.3的好像破解有问题，就索性改成2022.1的了
> 
> 
> 
> ---原始邮件---
> 发件人: "犬小哈教程 ***@***.***&gt;
> 发送时间: 2022年5月18日(周三) 上午9:41
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [weiwosuoai/weiwosuoai.github.io] idea激活码2020.2.2_idea注册码2020.2.2_idea2020.2.2破解（可激活至2089年，亲测有效） | 犬小哈教程网 (#70)
> 
> 
> 
> 
>   
> @CHENbt
>  使用30 天无限的方式，执行插件报错了，大佬，可以帮忙看一下吗
>   
> IDAE 版本是 2021.2.2 不
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2021.2.2 版本后，重置插件都不好使了
